"""empty message

Revision ID: 08409af9b351
Revises: d70b4541e4a1
Create Date: 2024-09-27 18:07:51.932609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08409af9b351'
down_revision = 'd70b4541e4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters__favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chracters_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'characters', ['chracters_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('following_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['following_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])
        batch_op.drop_column('title')

    with op.batch_alter_table('planets__favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets__favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planets_id')
        batch_op.drop_column('users_id')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('follower_id')
        batch_op.drop_column('following_id')

    with op.batch_alter_table('characters__favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chracters_id')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###
