"""empty message

Revision ID: 177935e056ff
Revises: 08409af9b351
Create Date: 2024-09-27 18:21:16.025538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177935e056ff'
down_revision = '08409af9b351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character__favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('chracters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chracters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet__favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets__favorites')
    op.drop_table('characters__favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters__favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chracters_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chracters_id'], ['characters.id'], name='characters__favorites_chracters_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='characters__favorites_users_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='characters__favorites_pkey')
    )
    op.create_table('planets__favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='planets__favorites_planets_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='planets__favorites_users_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planets__favorites_pkey')
    )
    op.drop_table('planet__favorites')
    op.drop_table('character__favorites')
    # ### end Alembic commands ###
