"""empty message

Revision ID: d70b4541e4a1
Revises: eabba67d37e4
Create Date: 2024-09-27 17:56:43.676969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70b4541e4a1'
down_revision = 'eabba67d37e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('followers_following_id_fkey', type_='foreignkey')
        batch_op.drop_column('following_id')

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('followers_following_id_fkey', 'users', ['following_id'], ['id'])

    # ### end Alembic commands ###
